from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from app.db.models import Job, OutboxEvent, Task, TtsCache


class IJobRepository(Protocol):
    async def create(self, job: Job) -> None: ...
    async def get(self, job_id: str) -> Job | None: ...
    async def transition_status(
        self, job_id: str, from_status: str, to_status: str
    ) -> bool: ...
    async def mark_failed(self, job_id: str, error: str) -> None: ...
    async def mark_completed(self, job_id: str, final_key: str) -> None: ...


class ITaskRepository(Protocol):
    async def create(self, task: Task) -> None: ...
    async def get(self, task_id: str) -> Task | None: ...
    async def get_by_job_stage(self, job_id: str, stage: str) -> Task | None: ...
    async def claim(
        self, task_id: str, worker_id: str, lease_seconds: int
    ) -> bool: ...
    async def complete(self, task_id: str, output_ref: str) -> None: ...
    async def fail(self, task_id: str, error: str, increment_attempts: bool = True) -> None: ...
    async def mark_dead(self, task_id: str, error: str) -> None: ...
    async def find_expired_leases(self, cutoff: datetime) -> list[Task]: ...
    async def reset_to_queued(self, task_id: str) -> None: ...


class IOutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...
    async def fetch_unpublished(self, limit: int) -> list[OutboxEvent]: ...
    async def mark_published(self, event_id: int) -> None: ...
    async def mark_failed(self, event_id: int) -> None: ...
    async def prune_published(self, older_than: datetime) -> int: ...


class IProcessedEventRepository(Protocol):
    async def record(self, event_id: str, stage: str) -> bool: ...


class ITtsCacheRepository(Protocol):
    async def get(self, text_hash: str) -> TtsCache | None: ...
    async def set(self, text_hash: str, object_key: str) -> None: ...
